### PR TITLE
add sudo as a service for bob's HBAC rule.

### PR DESCRIPTION
**Pull request by fcami**
As per https://access.redhat.com/solutions/3679241 sudo now needs to be added to the list of services of the HBAC rule.

### CODE REVIEW

**Comment by tscherf** [comment]
This is actually the fix for the issue I filed some time ago: https://github.com/freeipa/freeipa-workshop/issues/20

**Comment by fcami** [comment]
Oh, that's exactly it. 

@tscherf I didn't have to use "--hbacsvcs su-l" probably because I ssh'd directly into the VM as the correct user. Would you like me to add it too if it's required?

**Comment by tscherf** [comment]
> Oh, that's exactly it.
> 
> @tscherf I didn't have to use "--hbacsvcs su-l" probably because I ssh'd directly into the VM as the correct user. Would you like me to add it too if it's required?

If you can give it a try and then add the missing services to the hbac rules that would be fantastic.

**Comment by fcami** [comment]
Checked and updated, thanks for the heads-up @tscherf !

**Comment by frasertweedale** [comment]
Thank you @fcami and @tscherf !

**Pull request merged**
